"""Add rank to TeamMembership

Revision ID: 7113b5ca723d
Revises: d5fd3de55a67
Create Date: 2024-09-03 19:38:37.963115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7113b5ca723d'
down_revision = 'd5fd3de55a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_membership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_membership', schema=None) as batch_op:
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
