"""Add rank column to TeamMembership

Revision ID: 9feb15dacd38
Revises: 7113b5ca723d
Create Date: 2024-09-03 20:11:23.697918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9feb15dacd38'
down_revision = '7113b5ca723d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_membership', schema=None) as batch_op:
        batch_op.alter_column('rank',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_membership', schema=None) as batch_op:
        batch_op.alter_column('rank',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
